add-panic-variants = "true"
no-context = "true"
pkgname = "cargo_db"
output = "models"

[postgres]
  dbname  = "new-cargo"
  host    = "localhost"
  port    = "5432"
  user    = "wacai"
  sslmode = "disable"
