// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package cargo_db

var TableNames = struct {
	Roles         string
	Subscriptions string
	Tenants       string
	Users         string
}{
	Roles:         "roles",
	Subscriptions: "subscriptions",
	Tenants:       "tenants",
	Users:         "users",
}
